from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from skyhook.model import ModelError

try:
    from skyhook.model import chat_json
except ImportError:  # Skyhook < 0.4.0: degrade to static distillation
    chat_json = None

from .artifacts import load_json_artifact
from .document import _read_entries, _slug


MAX_RULES = 18
MAX_AREA_RULES = 12
MAX_THEME_RULES = 6
MAX_SOURCE_IDS = 6
RECENT_WINDOW = 20
MODEL_ENTRY_LIMIT = 100

_STOPWORDS = {
    "about", "after", "again", "against", "always", "because", "been", "before",
    "behavior", "being", "between", "changes", "could", "does", "doing", "each",
    "explicit", "from", "have", "instead", "into", "less", "make", "more", "most",
    "must", "need", "needs", "only", "other", "over", "should", "some", "still",
    "such", "than", "that", "their", "them", "then", "there", "these", "they",
    "this", "those", "under", "very", "were", "what", "when", "where", "which",
    "while", "will", "with", "would",
}


def source_fingerprint(entries: List[Mapping[str, Any]]) -> str:
    ids = sorted(str(entry.get("id", "")) for entry in entries)
    return hashlib.sha256("\n".join(ids).encode("utf-8")).hexdigest()[:16]


def build_or_reuse_rules(
    out_dir: Path,
    skyhook_cfg: Any,
    provider_override: Optional[str],
    allow_model: bool,
    refresh: bool = False,
) -> Dict[str, Any]:
    entries = _read_entries(out_dir / "worklog")
    fingerprint = source_fingerprint(entries)
    previous = load_json_artifact(out_dir, "agent-rules.json")
    if previous and previous.get("sourceFingerprint") == fingerprint and not refresh:
        return previous

    rules: Optional[List[Dict[str, Any]]] = None
    generated_by = "static"
    if allow_model and chat_json is not None and entries:
        try:
            rules = _model_rules(entries, previous, skyhook_cfg, provider_override)
            if rules is not None:
                generated_by = f"model:{_model_label(skyhook_cfg)}"
        except ModelError as exc:
            print(f"burnplan: rule distillation model failed, using static rules: {exc}", file=sys.stderr)
            rules = None
    if rules is None:
        rules = _static_rules(entries)
    return {
        "schemaVersion": 1,
        "sourceFingerprint": fingerprint,
        "generatedBy": generated_by,
        "ruleCount": len(rules),
        "rules": rules,
    }


def render_agent_rules_markdown(artifact: Mapping[str, Any]) -> str:
    lines = [
        "# Agent Rules",
        "",
        "<!-- GENERATED by burnplan. Review and edit this BurnPlan proposal before treating it as project truth. -->",
        "",
        f"- Generated by: `{artifact.get('generatedBy', 'static')}`",
        f"- Source fingerprint: `{artifact.get('sourceFingerprint', '')}`",
        f"- Rules: {artifact.get('ruleCount', 0)}",
        "",
        "## Rules",
        "",
    ]
    rules = artifact.get("rules") or []
    if rules:
        for rule in rules:
            area = rule.get("area") or "general"
            sources = ", ".join(rule.get("sourceIds") or []) or "none"
            lines.append(
                f"- **{rule.get('id', '')}** ({area}, {rule.get('status', 'active')}): "
                f"{rule.get('statement', '')} — sources: {sources}"
            )
    else:
        lines.append("- No rules distilled yet. Record work with `burnplan document` to build the evidence base.")
    lines.extend(
        [
            "",
            "## Lifecycle",
            "",
            "- Retire a rule when its error class stops recurring.",
            "- Rules marked `stale` had no supporting entries among recent work; review and remove them if obsolete.",
            "- Keep this set small and curated; a long rules file becomes noise agents skim past.",
            "",
        ]
    )
    return "\n".join(lines)


def _static_rules(entries: List[Mapping[str, Any]]) -> List[Dict[str, Any]]:
    if not entries:
        return []
    recent_areas = {_area(entry) for entry in entries[:RECENT_WINDOW]}
    recent_terms = set()
    for entry in entries[:RECENT_WINDOW]:
        recent_terms.update(_terms(str(entry.get("why", ""))))

    groups: Dict[str, List[Mapping[str, Any]]] = {}
    for entry in entries:
        groups.setdefault(_area(entry), []).append(entry)

    area_rules: List[Dict[str, Any]] = []
    ranked = sorted(groups.items(), key=lambda item: (-len(item[1]), item[0]))
    for area, group in ranked[:MAX_AREA_RULES]:
        area_rules.append(
            {
                "id": f"area-{_slug(area)}",
                "statement": _area_statement(area, group),
                "area": area,
                "sourceIds": _source_ids(group),
                "status": "active" if area in recent_areas else "stale",
            }
        )
    area_rules.sort(key=lambda rule: rule["id"])

    term_groups: Dict[str, List[Mapping[str, Any]]] = {}
    for entry in entries:
        for term in set(_terms(str(entry.get("why", "")))):
            term_groups.setdefault(term, []).append(entry)
    theme_rules: List[Dict[str, Any]] = []
    theme_ranked = sorted(
        (item for item in term_groups.items() if len(item[1]) >= 3),
        key=lambda item: (-len(item[1]), item[0]),
    )
    for term, group in theme_ranked[:MAX_THEME_RULES]:
        areas = sorted({_area(entry) for entry in group})
        theme_rules.append(
            {
                "id": f"theme-{term}",
                "statement": (
                    f'Recent rationale repeatedly cites "{term}" across {", ".join(areas)}; '
                    "read the source entries before changing related behavior."
                ),
                "area": "",
                "sourceIds": _source_ids(group),
                "status": "active" if term in recent_terms else "stale",
            }
        )
    theme_rules.sort(key=lambda rule: rule["id"])
    return (area_rules + theme_rules)[:MAX_RULES]


def _model_rules(
    entries: List[Mapping[str, Any]],
    previous: Optional[Mapping[str, Any]],
    skyhook_cfg: Any,
    provider_override: Optional[str],
) -> Optional[List[Dict[str, Any]]]:
    if chat_json is None:
        return None
    recent = [
        {
            "id": entry.get("id", ""),
            "area": entry.get("area", ""),
            "what": entry.get("what", ""),
            "why": entry.get("why", ""),
        }
        for entry in entries[:MODEL_ENTRY_LIMIT]
    ]
    previous_rules = list((previous or {}).get("rules") or [])
    messages = [
        {
            "role": "system",
            "content": (
                "You distill agent worklog entries into a small set of durable behavioral rules "
                "for future coding agents working in this repository. Return only valid JSON."
            ),
        },
        {
            "role": "user",
            "content": (
                "Distill at most 18 behavioral rules from these worklog entries. Each rule states what "
                "future agents should do or preserve, grounded in recurring rationale. Prefer fewer, "
                "stronger rules. Keep existing rules that are still supported, rephrasing only when it "
                "clearly improves them.\n\n"
                'Return JSON: {"rules": [{"statement": "...", "area": "...", "sourceIds": ["..."]}]}\n'
                "sourceIds must be ids of supporting entries.\n\n"
                "Existing rules:\n"
                + json.dumps(previous_rules, ensure_ascii=False)
                + "\n\nWorklog entries (newest first):\n"
                + json.dumps(recent, ensure_ascii=False)
            ),
        },
    ]
    result = chat_json(skyhook_cfg, messages, provider_override)
    if result is None:
        return None
    valid_ids = {str(entry.get("id", "")) for entry in entries}
    recent_areas = {_area(entry) for entry in entries[:RECENT_WINDOW]}
    previous_by_statement = {
        str(rule.get("statement", "")): str(rule.get("id", ""))
        for rule in previous_rules
        if rule.get("id")
    }
    rules: List[Dict[str, Any]] = []
    for raw in list(result.get("rules") or [])[:MAX_RULES]:
        if not isinstance(raw, Mapping):
            continue
        statement = str(raw.get("statement", "")).strip()
        if not statement:
            continue
        area = str(raw.get("area", "")).strip()
        source_ids = sorted({str(item) for item in (raw.get("sourceIds") or []) if str(item) in valid_ids})
        rule_id = previous_by_statement.get(statement) or "m-" + hashlib.sha256(statement.encode("utf-8")).hexdigest()[:8]
        rules.append(
            {
                "id": rule_id,
                "statement": statement,
                "area": area,
                "sourceIds": source_ids[:MAX_SOURCE_IDS],
                "status": "active" if not area or area in recent_areas else "stale",
            }
        )
    if not rules:
        return None
    rules.sort(key=lambda rule: rule["id"])
    return rules


def _area(entry: Mapping[str, Any]) -> str:
    return str(entry.get("area", "")).strip() or "general"


def _area_statement(area: str, group: List[Mapping[str, Any]]) -> str:
    counts: Dict[str, int] = {}
    for entry in group:
        for term in set(_terms(str(entry.get("why", "")))):
            counts[term] = counts.get(term, 0) + 1
    recurring = sorted(
        (term for term, count in counts.items() if count >= 2),
        key=lambda term: (-counts[term], term),
    )[:4]
    if recurring:
        return (
            f"When working in {area}, review the recorded rationale first; "
            f"recurring concerns: {', '.join(recurring)}."
        )
    why = str(group[0].get("why", "")).strip()
    first_sentence = re.split(r"(?<=[.!?])\s", why)[0].strip() if why else ""
    if first_sentence:
        return f"When working in {area}, honor the recorded rationale: {first_sentence}"
    return f"When working in {area}, read the worklog and rationale entries for that area before changing behavior."


def _source_ids(group: List[Mapping[str, Any]]) -> List[str]:
    return sorted(str(entry.get("id", "")) for entry in group)[:MAX_SOURCE_IDS]


def _terms(text: str) -> List[str]:
    return [
        token
        for token in re.findall(r"[a-z0-9]+", text.lower())
        if len(token) >= 4 and token not in _STOPWORDS
    ]


def _model_label(skyhook_cfg: Any) -> str:
    requested = os.environ.get("SKYHOOK_MODEL") or getattr(getattr(skyhook_cfg, "model", None), "model", "")
    return requested if requested and requested != "auto" else "default"
