from __future__ import annotations

from typing import Any, Mapping


def render_onboarding_markdown(data: Mapping[str, Any]) -> str:
    lines = ["# BurnPlan Onboarding", "", "<!-- GENERATED by burnplan. -->", ""]
    lines.extend(["## Summary", "", data.get("summary") or "No onboarding summary captured.", ""])
    _section_list(lines, "Functional Requirements", data.get("functionalRequirements", []))
    _section_list(lines, "Non-Functional Requirements", data.get("nonFunctionalRequirements", []))
    architecture_intent = data.get("architectureIntent")
    if architecture_intent:
        lines.extend(["## Architecture Intent", "", str(architecture_intent), ""])
    _section_list(lines, "Short-Term Goals", data.get("shortTermGoals", []))
    _section_list(lines, "Long-Term Goals", data.get("longTermGoals", []))
    _section_list(lines, "Risk Areas", data.get("riskAreas", []))

    lines.extend(["## Documentation Gaps", ""])
    gaps = data.get("documentationGaps", []) or []
    if gaps:
        for gap in gaps:
            lines.append(f"- `{gap.get('kind', 'unknown')}` ({gap.get('priority', 'medium')}): {gap.get('recommendation', '')}")
    else:
        lines.append("- No documentation gaps detected.")
    lines.append("")

    lines.extend(["## Suggested Documents", ""])
    suggested = data.get("suggestedDocs", []) or []
    if suggested:
        for doc in suggested:
            lines.append(f"- `{doc.get('path')}` ({doc.get('priority', 'medium')}): {doc.get('reason', '')}")
    else:
        lines.append("- None.")
    lines.append("")

    lines.extend(["## Interview Answers", ""])
    answers = data.get("interviewAnswers", []) or []
    if answers:
        for item in answers:
            answer = item.get("answer") or "Not captured."
            lines.append(f"### {item.get('question')}")
            lines.append("")
            lines.append(answer)
            lines.append("")
    else:
        lines.append("No interview answers captured.")
        lines.append("")
    return "\n".join(lines)


def render_quality_markdown(data: Mapping[str, Any]) -> str:
    source = data.get("source", {}) or {}
    lines = [
        "# BurnPlan Quality",
        "",
        "<!-- GENERATED by burnplan. -->",
        "",
        "## Source",
        "",
        f"- Type: `{source.get('type', 'unknown')}`",
        f"- Available: `{source.get('available', False)}`",
        f"- Commits analyzed: `{source.get('commitsAnalyzed', 0)}`",
        f"- Window: `{source.get('sinceDays', 0)}` days, max `{source.get('maxCommits', 0)}` commits",
        "",
    ]
    if source.get("message"):
        lines.extend([str(source["message"]), ""])

    lines.extend(["## Weak Points", ""])
    _bullet_values(lines, data.get("weakPoints", []) or ["No weak points detected."])

    lines.extend(["## Hotspots", ""])
    hotspots = data.get("hotspots", []) or []
    if hotspots:
        lines.append("| Path | Revisions | Last Touched | Kind | Language |")
        lines.append("|---|---:|---|---|---|")
        for item in hotspots:
            lines.append(
                f"| `{item.get('path', '')}` | {item.get('revisions', 0)} | `{item.get('lastTouched', '')}` | {item.get('kind', '')} | {item.get('language', '')} |"
            )
    else:
        lines.append("No hotspots detected.")
    lines.append("")

    lines.extend(["## Coupling", ""])
    couplings = data.get("couplings", []) or []
    if couplings:
        lines.append("| Files | Co-Changes |")
        lines.append("|---|---:|")
        for item in couplings:
            paths = item.get("paths", []) or []
            lines.append(f"| {', '.join('`' + path + '`' for path in paths)} | {item.get('changes', 0)} |")
    else:
        lines.append("No repeated co-change pairs detected.")
    lines.append("")

    lines.extend(["## Volatile Areas", ""])
    areas = data.get("volatileAreas", []) or []
    if areas:
        for item in areas:
            lines.append(f"- `{item.get('area', '')}`: {item.get('revisions', 0)} recent revisions")
    else:
        lines.append("- None detected.")
    lines.append("")

    lines.extend(["## Static Analysis", ""])
    static_analysis = data.get("staticAnalysis", {}) or {}
    tools = static_analysis.get("tools", []) or []
    if tools:
        for tool in tools:
            lines.append(f"- `{tool.get('name', '')}` via `{tool.get('marker', '')}`")
    else:
        lines.append("- No static analysis configuration detected.")
    if static_analysis.get("message"):
        lines.append(f"- {static_analysis['message']}")
    lines.append("")
    return "\n".join(lines)


def render_agent_prompts_markdown(data: Mapping[str, Any]) -> str:
    lines = ["# BurnPlan Agent Prompts", "", "<!-- GENERATED by burnplan. -->", ""]
    _section_list(lines, "Read First", data.get("readFirst", []), code=True)
    _section_list(lines, "Before Coding", data.get("beforeCoding", []))
    _section_list(lines, "Before Commit Or PR", data.get("beforeCommit", []))
    evidence = data.get("documentationEvidence", {}) or {}
    lines.extend(["## Documentation Evidence", ""])
    lines.append(f"- Worklog entries: `{evidence.get('worklogCount', 0)}`")
    lines.append(f"- Rationale entries: `{evidence.get('rationaleCount', 0)}`")
    lines.append("")
    return "\n".join(lines)


def render_documentation_ledger_markdown(data: Mapping[str, Any]) -> str:
    lines = [
        "# BurnPlan Documentation Ledger",
        "",
        "<!-- GENERATED by burnplan. -->",
        "",
        f"- Worklog entries: `{data.get('worklogCount', 0)}`",
        f"- Rationale entries: `{data.get('rationaleCount', 0)}`",
        "",
    ]
    lines.extend(["## Recent Work", ""])
    _entry_table(lines, data.get("recentWork", []) or [])
    lines.extend(["## Recent Rationale", ""])
    _entry_table(lines, data.get("recentRationale", []) or [])
    return "\n".join(lines)


def _section_list(lines: list[str], title: str, values: Any, code: bool = False) -> None:
    lines.extend([f"## {title}", ""])
    if values:
        for value in values:
            text = f"`{value}`" if code else str(value)
            lines.append(f"- {text}")
    else:
        lines.append("- None captured.")
    lines.append("")


def _bullet_values(lines: list[str], values: Any) -> None:
    for value in values:
        lines.append(f"- {value}")
    lines.append("")


def _entry_table(lines: list[str], entries: Any) -> None:
    if not entries:
        lines.append("No entries yet.")
        lines.append("")
        return
    lines.append("| Timestamp | Area | Summary |")
    lines.append("|---|---|---|")
    for entry in entries:
        summary = str(entry.get("what") or entry.get("why") or "").replace("\n", " ")[:120]
        lines.append(f"| `{entry.get('timestamp', '')}` | `{entry.get('area', '')}` | {summary} |")
    lines.append("")
